language: python

python:
  # This is not actually used. Because it would take an overly long time
  # to build scipy we cannot use the virtual env of travis. Instead, we
  # use miniconda.
  - 2.7

install:
  - sudo apt-get update -qq

  # Install miniconda
  # -----------------
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p ~/miniconda
  - export PATH="~/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  # See https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  - conda update --no-deps conda
  - conda update conda
  # Pin Python version to 2.7.8 to temporarily work around SSL verification
  # enforcement introduced in Python 2.7.9.
  - conda create -n test-env python=2.7.8
  - source activate test-env

  # Customise the testing environment
  # ---------------------------------
  - conda config --add channels rsignell
  - conda config --add channels pelson
  - conda install numpy=1.7.1 matplotlib=1.3.1 scipy=0.12.0
  - conda install cython
  - conda install pillow
  - conda install mock
  - conda install nose
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      conda install owslib;
    fi
  - conda install pep8
  - conda install proj4
  - conda install pyshp
  - conda install shapely=1.4.3
  - conda install six

  - conda install requests
  - conda install pip
  - conda install pyepsg

  # Conda debug
  # -----------
  - conda list

  - MPL_CONFIG_DIR=~/.config/matplotlib
  - mkdir -p $MPL_CONFIG_DIR
  - echo "backend" ":" "agg" > $MPL_CONFIG_DIR/matplotlibrc

  # Install cartopy
  # ---------------
  - python setup.py --quiet install

script:
  - mkdir ../test_folder
  - cd ../test_folder
  - nosetests cartopy --with-doctest -sv

after_failure:
  - source activate test-env
  - python -c "import cartopy.tests.mpl; print cartopy.tests.mpl.failed_images_html()"
